### ISSUE TITLE
Windows build Login BUG

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source#195] opened 2019-09-15 12:35 UTC
I have an intermitent bug. Some account seem to be ban for the server... After connecting, the server kick the user out....  If user use an other account, all work well.

This degub screen can help?

![image](https://user-images.githubusercontent.com/51728381/64972896-15819600-d878-11e9-8d94-2cfefa04afda.png)

 
Bug occur with 2 Clients Orion and cross UO

**Comment by coruja747** [comment] 2019-09-15 18:49
Try using an previous build to check what's the last build working (eg: build 123 = working fine, build 124 = error). With this info we would know exactly what changes caused the error, making it easier to fix

Here you can find all recent builds to download, just click on the build, select Visual Studio (windows build), click on Artifacts page and download the zip
https://ci.appveyor.com/project/coruja747/source/history

**Comment by Jhobean** [comment] 2019-09-16 15:37
It's an intermittent bug so it's really difficult to test. I'll let you know if I found a patern.

**Comment by Jhobean** [comment] 2019-09-18 03:01
At this time, this build FAIL : 0.56.4.896
Now testing  0.56.4.895

**Comment by Jhobean** [comment] 2019-09-19 22:10
At this time, Bug seem between 94 and 95

**Comment by Jhobean** [comment] 2019-09-21 14:34
@coruja747  I confirm the bug seem to provide from this commit:
https://github.com/Sphereserver/Source/commit/ee1bf26bf23521ca64569c3cc18bc534e52b6679

**Comment by Jhobean** [comment] 2019-09-22 17:11
Make a hold. Just had the bug with build 94 again.....

**Comment by Nirad** [comment] 2019-09-25 04:33
@coruja747 I can't find the problem off this #193 #196

**Comment by coruja747** [comment] 2019-09-26 05:24
Try using this test build https://ci.appveyor.com/api/buildjobs/6ji2yqat3xcu7r8v/artifacts/SphereSvr-Win32-Test.zip

It's the latest 56d build with just an extra debug message to track this error, so when you get this error again just copy/paste it here

**Comment by Jhobean** [comment] 2019-09-26 10:54
Ok thx. Let me few days

**Comment by FiLoUs64** [comment] 2019-09-26 12:25
Got this after a login 

08:25:DEBUG:__ thread (1696) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
08:25:DEBUG:>>         1696     |  0 |                 NetworkManager::tick | +0 
08:25:DEBUG:>>         1696     |  1 |                  NetworkThread::tick | +0 
08:25:DEBUG:>>         1696     |  2 |           NetworkInput::processInput | +0 
08:25:DEBUG:>>         1696     |  3 |            NetworkInput::processData | +0 
08:25:DEBUG:>>         1696     |  4 |            NetworkInput::processData | +0 
08:25:DEBUG:>>         1696     |  5 | NetworkInput::processUnknownClientData | +0 
08:25:DEBUG:>>         1696     |  6 |         CClient::xProcessClientSetup | +0 
08:25:DEBUG:>>         1696     |  7 |            CClient::Login_ServerList | +0 
08:25:DEBUG:>>         1696     |  8 |                       CClient::LogIn | +0 
08:25:DEBUG:>>         1696     |  9 |                      CClient::LogIn2 | +0 <-- exception catch point (below is guessed and could be incorrect!)
08:25:CRITICAL:"Access Violation" (0xfb9e6), in CClient::Account login() #2 "Check in use"
08:25:DEBUG:__ thread (1696) __ |  # | _____________ function _____________ | __ ticks passed from previous function start __
08:25:DEBUG:>>         1696     |  0 |                 NetworkManager::tick | +0 
08:25:DEBUG:>>         1696     |  1 |                  NetworkThread::tick | +0 
08:25:DEBUG:>>         1696     |  2 |           NetworkInput::processInput | +0 
08:25:DEBUG:>>         1696     |  3 |            NetworkInput::processData | +0 
08:25:DEBUG:>>         1696     |  4 |            NetworkInput::processData | +0 
08:25:DEBUG:>>         1696     |  5 |  NetworkInput::processGameClientData | +0 
08:25:DEBUG:>>         1696     |  6 |        PacketServerSelect::onReceive | +0 
08:25:DEBUG:>>         1696     |  7 |                 CClient::Login_Relay | +0 
08:25:DEBUG:>>         1696     |  8 |                    CClient::addRelay | +0 <-- exception catch point (below is guessed and could be incorrect!)
08:25:CRITICAL:"Access Violation" (0x93895), in CClient::addRelay() #1 "customer id"
08:25:DEBUG:account ''

**Comment by coruja747** [comment] 2019-09-26 16:45
The problem seems to be when server check if the account is already in use, I added more specific debug messages to track this, try using this new build and check the console error again
https://ci.appveyor.com/api/buildjobs/ca9e3kb6b3ywpffg/artifacts/SphereSvr-Win32-Test.zip

**Comment by Nirad** [comment] 2019-09-26 22:14
Thx we will give a try !
and feedback after

**Comment by FiLoUs64** [comment] 2019-09-27 13:41
Not been able to reproduce the issue BUT I have a lot a problem for login, always have a message like what the account is already in use after logout.

**Comment by Nirad** [comment] 2019-09-27 15:45
This can't help ?
![2](https://user-images.githubusercontent.com/359353/65782701-42596700-e11c-11e9-8c99-7ecd1be31b3f.png)
![1](https://user-images.githubusercontent.com/359353/65782702-42596700-e11c-11e9-89fb-05b87faa6130.png)

**Comment by coruja747** [comment] 2019-09-28 04:42
This visual code debug show basically the same thing of sphere exceptions, or in other words, sphere stack trace was made to show these same debug exceptions without need any external tool

Anyway, on latest build I changed some things to improve account connection process, try using this build to check if it's working fine

**Comment by Nirad** [comment] 2019-09-29 22:56
![Capture d’écran 2019-09-29 à 18 56 28](https://user-images.githubusercontent.com/359353/65840771-e0029100-e2ea-11e9-974d-75b05266ecfe.png)
latest build

**Comment by coruja747** [comment] 2019-09-30 10:01
I did some few more improvements, try download latest build (909) again

**Comment by Nirad** [comment] 2019-09-30 17:59
Perfect now trying 909 with 7e9f77dd2c0f80280c97af2e26b0eda1f867214d and 6c5bdae6de99cd310aff27d400b45abb978040ba

**Comment by Nirad** [comment] 2019-10-01 04:04
after a day no error I will give it 1 more day!

**Comment by Nirad** [comment] 2019-10-03 00:38
All good for now, Close this !

**Comment by Jhobean** [comment] 2019-10-03 10:11
Thx for your help coruja

**Comment by FiLoUs64** [comment] 2019-10-07 01:01
![image](https://user-images.githubusercontent.com/47130805/66279032-80712c00-e87c-11e9-884a-bfa0a05bb65d.png)
Same problem again...

**Comment by coruja747** [comment] 2019-10-07 01:45
This was already fixed but I accidentally reverted the fix, but anyway I fixed it again on latest build, try check if it's working fine now

**Closed** 2019-10-09 03:04 UTC
Labels: fixed
